// Generated by https://quicktype.io

export interface IOrder {
  orderId: number;
  customerEmail: string;
  customerFirstname: string;
  customerLastname: string;
  subtotal: number;
  baseSubtotal: null;
  totalAmount: number;
  totalPriceWeight: number;
  statusPaymentActual: string;
  status: string;
  transactionId: string;
  orderDetails: OrderDetail[];
  historyPayments: HistoryPayment[];
}

export interface HistoryPayment {
  status: string;
  description: string;
  data: string;
}

export interface OrderDetail {
  productName: string;
  orderId: number;
  isVirtual: boolean;
  skuCode: string;
  description: null;
  freeShipping: boolean;
  quantity: number;
  price: number;
  weight: number;
}
